### PR TITLE
Invoca 3.2.22.2 TECH-1090

### PR DESCRIPTION
**Pull request by omeedrj**
@victorborda 

[Invoca Web TECH-1090 PR](https://github.com/Invoca/web/pull/5474)

[Rails 4 Upgrade Spreadsheet](https://docs.google.com/spreadsheets/d/15fmPhaXyDJBdzzHccBBjqXHgbBez23lWoH09SqMLytk/edit#gid=0)

### CODE REVIEW

**Comment by victorborda** [comment]
we need to keep the changes in active_record/fixtures.rb for now
we use them as part of our scenario generation
@primiti - would love to get your eyes on the changes to the first 2 files here. as for fixtures.rb, we need to keep that unless we switch over default fixtures into a scenario right? maybe we can pull this out and override in config/initializers ?

**Comment by omeedrj** [comment]
patches for fixtures.rb were restored

**Comment by victorborda** [comment]
ok, I think these two changes are good, but you will definitely want to run script/regen using them and make sure it succeeds and tests pass afterwards.

**Comment by primiti** [comment]
I _believe_ the intent here is to roll back our patches so that the existing code matches stock rails.  I am assuming that these changes accomplish this. 

The check-for-existence pattern was there because we had issues with index names moving and generating migrations that could not be run in production.    We may run into this again, but when we do we should fix it without patching rails.

**Comment by primiti** [comment]
Oh, so :+1:

**Pull request merged**
